"""
core/logger.py — Centralized logging to SQLite + rotating file.

Tables:
  signals    — every signal generated by the EA
  trades     — complete trade lifecycle records
  indicators — normalized feature snapshot per candle
  performance — daily performance snapshots
"""

import os
import sqlite3
import logging
import json
from logging.handlers import RotatingFileHandler
from datetime import datetime, timezone
from typing import Optional, Dict, Any

import config

# ─── File / Console Logger ────────────────────────────────────────────────────

class BeautifulConsoleFormatter(logging.Formatter):
    """Sleek and beautiful console logger formatter with custom icons and aligned tags."""
    
    def format(self, record: logging.LogRecord) -> str:
        # Time format: HH:MM:SS
        time_str = datetime.fromtimestamp(record.created).strftime("%H:%M:%S")
        
        # Determine icon based on log level
        level = record.levelname
        msg = record.getMessage()
        
        if level == "INFO":
            icon = " "
            if "HOLD" in msg:
                icon = "◆"
            elif "LONG" in msg:
                icon = "▲"
            elif "SHORT" in msg:
                icon = "▼"
            elif "====" in msg or "Crypto Futures" in msg or "Symbol:" in msg or "Mode:" in msg or "Thresholds:" in msg:
                # Keep division lines and headers clean without icons/timestamps
                return msg
        elif level == "WARNING":
            icon = "⚠"
        elif level == "ERROR":
            icon = "✗"
        elif level == "CRITICAL":
            icon = "🔥"
        else:
            icon = " "

        # Align tag names nicely, e.g. [Main] -> "[Main]        "
        name_part = f"[{record.name}]"
        name_aligned = f"{name_part:<12}"
        
        # Strip redundant name prefix if it exists in msg (e.g. "[Main] [EA] Starting..." -> "[EA] Starting...")
        clean_msg = msg
        redundant_prefix = f"[{record.name}]"
        if clean_msg.startswith(redundant_prefix):
            clean_msg = clean_msg[len(redundant_prefix):].strip()
            
        # Also clean common sub-prefixes to keep it extremely tidy
        for prefix in ["[EA]", "[ML]", "[Sentiment]", "[MarketData]", "[Exec]", "[Signal]"]:
            if clean_msg.startswith(prefix):
                clean_msg = clean_msg[len(prefix):].strip()
        
        return f"{time_str} | {icon} {name_aligned} | {clean_msg}"


def setup_logger(name: str = "EA") -> logging.Logger:
    os.makedirs(config.LOG_DIR, exist_ok=True)
    logger = logging.getLogger(name)
    if logger.handlers:
        return logger

    logger.setLevel(logging.DEBUG)

    # Rotating file handler (10 MB × 5 backups)
    fh = RotatingFileHandler(
        config.LOG_FILE, maxBytes=10 * 1024 * 1024, backupCount=5,
        encoding="utf-8"
    )
    fh.setLevel(logging.DEBUG)

    # Console handler
    ch = logging.StreamHandler()
    ch.setLevel(logging.INFO)

    file_fmt = logging.Formatter(
        "[%(asctime)s] [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    )
    fh.setFormatter(file_fmt)
    
    # Custom beautiful formatter for console
    ch.setFormatter(BeautifulConsoleFormatter())

    logger.addHandler(fh)
    logger.addHandler(ch)
    return logger


log = setup_logger()


# ─── SQLite DB Manager ────────────────────────────────────────────────────────

class DBLogger:
    """Thread-safe SQLite logger for the EA."""

    def __init__(self, db_path: str = config.DB_PATH):
        os.makedirs(os.path.dirname(db_path), exist_ok=True)
        self.db_path = db_path
        self._init_db()

    # ── Init ──────────────────────────────────────────────────────────────────

    def _get_conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path, timeout=10)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self):
        with self._get_conn() as conn:
            conn.executescript("""
            CREATE TABLE IF NOT EXISTS signals (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ts          TEXT NOT NULL,
                symbol      TEXT NOT NULL,
                timeframe   TEXT NOT NULL,
                action      TEXT NOT NULL,
                confidence  REAL,
                ml_long     REAL,
                ml_short    REAL,
                ml_hold     REAL,
                tech_score  REAL,
                sent_score  REAL,
                llm_adj     REAL,
                regime      TEXT,
                trend_dir   TEXT,
                raw_json    TEXT
            );

            CREATE TABLE IF NOT EXISTS trades (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                trade_id        TEXT UNIQUE,
                symbol          TEXT NOT NULL,
                side            TEXT NOT NULL,
                entry_ts        TEXT NOT NULL,
                exit_ts         TEXT,
                entry_price     REAL,
                exit_price      REAL,
                quantity        REAL,
                sl_price        REAL,
                tp_price        REAL,
                pnl_usdt        REAL,
                pnl_pct         REAL,
                duration_min    REAL,
                exit_reason     TEXT,
                confidence      REAL,
                status          TEXT DEFAULT 'OPEN'
            );

            CREATE TABLE IF NOT EXISTS indicators (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                ts              TEXT NOT NULL,
                symbol          TEXT NOT NULL,
                timeframe       TEXT NOT NULL,
                close           REAL,
                ema5_dist       REAL,
                ema20_dist      REAL,
                vwap_dist       REAL,
                atr_pct         REAL,
                volume_chg_pct  REAL,
                rsi_scaled      REAL,
                adx_scaled      REAL,
                macd_norm       REAL,
                regime          TEXT,
                trend_dir       TEXT
            );

            CREATE TABLE IF NOT EXISTS performance (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                date            TEXT UNIQUE,
                total_trades    INTEGER,
                winning_trades  INTEGER,
                win_rate        REAL,
                total_pnl       REAL,
                profit_factor   REAL,
                sharpe_ratio    REAL,
                max_drawdown    REAL,
                avg_duration    REAL
            );
            """)

    # ── Signal Logging ────────────────────────────────────────────────────────

    def log_signal(
        self,
        symbol: str,
        timeframe: str,
        action: str,
        confidence: float,
        ml_probs: Dict[str, float],
        tech_score: float,
        sent_score: float,
        llm_adj: float,
        regime: str,
        trend_dir: str,
        raw: Optional[Dict] = None,
    ):
        ts = datetime.now(timezone.utc).isoformat()
        with self._get_conn() as conn:
            conn.execute(
                """INSERT INTO signals
                   (ts, symbol, timeframe, action, confidence,
                    ml_long, ml_short, ml_hold, tech_score, sent_score, llm_adj,
                    regime, trend_dir, raw_json)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    ts, symbol, timeframe, action, confidence,
                    ml_probs.get("long", 0),
                    ml_probs.get("short", 0),
                    ml_probs.get("hold", 0),
                    tech_score, sent_score, llm_adj,
                    regime, trend_dir,
                    json.dumps(raw) if raw else None,
                ),
            )

    # ── Trade Logging ─────────────────────────────────────────────────────────

    def open_trade(
        self,
        trade_id: str,
        symbol: str,
        side: str,
        entry_price: float,
        quantity: float,
        sl_price: float,
        tp_price: float,
        confidence: float,
    ):
        ts = datetime.now(timezone.utc).isoformat()
        with self._get_conn() as conn:
            conn.execute(
                """INSERT OR IGNORE INTO trades
                   (trade_id, symbol, side, entry_ts, entry_price, quantity,
                    sl_price, tp_price, confidence, status)
                   VALUES (?,?,?,?,?,?,?,?,?,'OPEN')""",
                (trade_id, symbol, side, ts, entry_price, quantity,
                 sl_price, tp_price, confidence),
            )

    def close_trade(
        self,
        trade_id: str,
        exit_price: float,
        pnl_usdt: float,
        pnl_pct: float,
        duration_min: float,
        exit_reason: str,
    ):
        ts = datetime.now(timezone.utc).isoformat()
        with self._get_conn() as conn:
            conn.execute(
                """UPDATE trades
                   SET exit_ts=?, exit_price=?, pnl_usdt=?, pnl_pct=?,
                       duration_min=?, exit_reason=?, status='CLOSED'
                   WHERE trade_id=?""",
                (ts, exit_price, pnl_usdt, pnl_pct, duration_min, exit_reason, trade_id),
            )

    # ── Indicator Snapshot ────────────────────────────────────────────────────

    def log_indicators(self, symbol: str, timeframe: str, feats: Dict[str, Any]):
        ts = datetime.now(timezone.utc).isoformat()
        with self._get_conn() as conn:
            conn.execute(
                """INSERT INTO indicators
                   (ts, symbol, timeframe, close,
                    ema5_dist, ema20_dist, vwap_dist, atr_pct,
                    volume_chg_pct, rsi_scaled, adx_scaled, macd_norm,
                    regime, trend_dir)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (
                    ts, symbol, timeframe,
                    feats.get("close"),
                    feats.get("ema5_dist"),
                    feats.get("ema20_dist"),
                    feats.get("vwap_dist"),
                    feats.get("atr_pct"),
                    feats.get("volume_change_pct"),
                    feats.get("rsi_scaled"),
                    feats.get("adx_scaled"),
                    feats.get("macd_norm"),
                    feats.get("regime"),
                    feats.get("trend_dir"),
                ),
            )

    # ── Performance Snapshot ──────────────────────────────────────────────────

    def upsert_performance(self, perf: Dict[str, Any]):
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        with self._get_conn() as conn:
            conn.execute(
                """INSERT INTO performance
                   (date, total_trades, winning_trades, win_rate, total_pnl,
                    profit_factor, sharpe_ratio, max_drawdown, avg_duration)
                   VALUES (?,?,?,?,?,?,?,?,?)
                   ON CONFLICT(date) DO UPDATE SET
                     total_trades=excluded.total_trades,
                     winning_trades=excluded.winning_trades,
                     win_rate=excluded.win_rate,
                     total_pnl=excluded.total_pnl,
                     profit_factor=excluded.profit_factor,
                     sharpe_ratio=excluded.sharpe_ratio,
                     max_drawdown=excluded.max_drawdown,
                     avg_duration=excluded.avg_duration""",
                (
                    date,
                    perf.get("total_trades", 0),
                    perf.get("winning_trades", 0),
                    perf.get("win_rate", 0),
                    perf.get("total_pnl", 0),
                    perf.get("profit_factor", 0),
                    perf.get("sharpe_ratio", 0),
                    perf.get("max_drawdown", 0),
                    perf.get("avg_duration", 0),
                ),
            )

    # ── Query Helpers ─────────────────────────────────────────────────────────

    def get_open_trade(self) -> Optional[Dict]:
        with self._get_conn() as conn:
            row = conn.execute(
                "SELECT * FROM trades WHERE status='OPEN' LIMIT 1"
            ).fetchone()
            return dict(row) if row else None

    def get_daily_pnl(self) -> float:
        today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        with self._get_conn() as conn:
            row = conn.execute(
                "SELECT COALESCE(SUM(pnl_usdt),0) as pnl FROM trades WHERE date(exit_ts)=? AND status='CLOSED'",
                (today,)
            ).fetchone()
            return float(row["pnl"]) if row else 0.0

    def get_recent_trades(self, n: int = 50) -> list:
        with self._get_conn() as conn:
            rows = conn.execute(
                "SELECT * FROM trades WHERE status='CLOSED' ORDER BY exit_ts DESC LIMIT ?", (n,)
            ).fetchall()
            return [dict(r) for r in rows]

    def get_recent_performance(self, n: int = 7) -> dict:
        """
        Ambil statistik performa dari N trade terakhir untuk Rolling Kelly Criterion.

        Returns:
            {
                "n_trades":   int,   # jumlah trade yang ditemukan
                "win_rate":   float, # persentase trade profit (0.0 - 1.0)
                "avg_win":    float, # rata-rata PnL saat profit (USDT)
                "avg_loss":   float, # rata-rata PnL saat rugi (absolute, USDT)
                "win_loss_r": float, # ratio avg_win / avg_loss
            }
        """
        trades = self.get_recent_trades(n=n)
        if not trades:
            return {
                "n_trades":   0,
                "win_rate":   0.5,   # Default netral jika belum ada data
                "avg_win":    1.0,
                "avg_loss":   1.0,
                "win_loss_r": 1.0,
            }

        wins  = [t["pnl_usdt"] for t in trades if (t.get("pnl_usdt") or 0) > 0]
        losses = [abs(t["pnl_usdt"]) for t in trades if (t.get("pnl_usdt") or 0) <= 0]

        win_rate  = len(wins) / len(trades)
        avg_win   = sum(wins)   / len(wins)   if wins   else 0.0
        avg_loss  = sum(losses) / len(losses) if losses else 1.0  # hindari div-by-zero
        win_loss_r = avg_win / avg_loss if avg_loss > 0 else 1.0

        return {
            "n_trades":   len(trades),
            "win_rate":   round(win_rate,   4),
            "avg_win":    round(avg_win,    4),
            "avg_loss":   round(avg_loss,   4),
            "win_loss_r": round(win_loss_r, 4),
        }
